In [2]:
import math
import numpy as np
import torch 
from torch import nn
from d2l import torch as d2l

In [46]:
max_degree = 20
n_train, n_test = 100 , 100
true_w = np.zeros(max_degree)
true_w[0:4] = np.array([5,1.2,-3.4,5.6])

features = np.random.normal(size=(n_train+n_test,1)) # 生成训练数据集,测试数据集,其实就是x的值
np.random.shuffle(features) # 将x的顺序打乱.增加随机性质
print(features.shape)
poly_features = np.power(features, np.arange(max_degree).reshape(1,-1)) # 将x进行1-20次方的幂运算,该方法将向量拓展为矩阵
print(poly_features.shape)
for i in range(max_degree):
    poly_features[:][i] /= math.gamma(i+1) # 除以n!
print(poly_features[:1])
labels = np.dot(poly_features, true_w) # 算出labels,也就是y
print(labels[:1])

(200, 1)
(200, 20)
[[ 1.00000000e+00 -1.74998621e+00  3.06245172e+00 -5.35924826e+00
   9.37861053e+00 -1.64124391e+01  2.87215420e+01 -5.02623022e+01
   8.79583356e+01 -1.53925874e+02  2.69368156e+02 -4.71390557e+02
   8.24926972e+02 -1.44361082e+03  2.52629903e+03 -4.42098844e+03
   7.73666879e+03 -1.35390637e+04  2.36931746e+04 -4.14627288e+04]]
[-37.52410957]


In [38]:
np.power([[1],[2],[3]],[1,2,1,1,1,1])

array([[1, 1, 1, 1, 1, 1],
       [2, 4, 2, 2, 2, 2],
       [3, 9, 3, 3, 3, 3]])

In [40]:
np.power([1,2,3,4,5,6],[[1],[2],[3]])

array([[  1,   2,   3,   4,   5,   6],
       [  1,   4,   9,  16,  25,  36],
       [  1,   8,  27,  64, 125, 216]])

array([ 5. ,  1.2, -3.4,  5.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ])