In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l


true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [2]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器。"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

# 使用框架预定义好的层

In [3]:
# `nn` 是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

# 初始化模型参数

In [4]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

# 计算均方误差使用的是MSELoss类，也称为平方L2范数

In [5]:
loss = nn.MSELoss()

# 实例化SGD实例

In [6]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

In [7]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000104
epoch 2, loss 0.000104
epoch 3, loss 0.000104
epoch 4, loss 0.000104
epoch 5, loss 0.000104
epoch 6, loss 0.000104
epoch 7, loss 0.000104
epoch 8, loss 0.000104
epoch 9, loss 0.000104
epoch 10, loss 0.000104


In [29]:
for x in net.parameters():
    print(x)

Parameter containing:
tensor([[ 1.9997, -3.4004]], requires_grad=True)
Parameter containing:
tensor([4.1998], requires_grad=True)


In [35]:
net[0].weight
net[0].bias.data

tensor([4.1998])